overrides:
  aidbox-fhirpath-lsp@0.0.0-alpha.1: link:../../Library/pnpm/global/5/node_modules/@health-samurai/aidbox-fhirpath-lsp@0.0.0-alpha.1
  react-components@0.0.0-alpha.10: link:../../Library/pnpm/global/5/node_modules/@health-samurai/react-components@0.0.0-alpha.10
