// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../hl7-fhir-r5-core/Coding";
import type { DataType } from "../hl7-fhir-r5-core/DataType";

export type { Coding } from "../hl7-fhir-r5-core/Coding";
export type { DataType } from "../hl7-fhir-r5-core/DataType";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/CodeableConcept
export interface CodeableConcept extends DataType {
	coding?: Coding[];
	text?: string;
	_text?: Element;
}
