// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { DataType } from "../hl7-fhir-r5-core/DataType";
import type { Period } from "../hl7-fhir-r5-core/Period";

export type { DataType } from "../hl7-fhir-r5-core/DataType";
export type { Period } from "../hl7-fhir-r5-core/Period";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ContactPoint
export interface ContactPoint extends DataType {
    period?: Period;
    rank?: number;
    _rank?: Element;
    system?: "phone" | "fax" | "email" | "pager" | "url" | "sms" | "other";
    _system?: Element;
    use?: "home" | "work" | "temp" | "old" | "mobile";
    _use?: Element;
    value?: string;
    _value?: Element;
}
