// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { ContactPoint } from "../hl7-fhir-r5-core/ContactPoint";
import type { DataType } from "../hl7-fhir-r5-core/DataType";

export type { ContactPoint } from "../hl7-fhir-r5-core/ContactPoint";
export type { DataType } from "../hl7-fhir-r5-core/DataType";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ContactDetail
export interface ContactDetail extends DataType {
    name?: string;
    _name?: Element;
    telecom?: ContactPoint[];
}
