// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../hl7-fhir-r5-core/Extension";
import type { Narrative } from "../hl7-fhir-r5-core/Narrative";
import type { Resource } from "../hl7-fhir-r5-core/Resource";

export type { Extension } from "../hl7-fhir-r5-core/Extension";
export type { Narrative } from "../hl7-fhir-r5-core/Narrative";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/DomainResource
export interface DomainResource extends Resource {
    resourceType: "CanonicalResource" | "DomainResource" | "ViewDefinition";

    contained?: Resource[];
    extension?: Extension[];
    modifierExtension?: Extension[];
    text?: Narrative;
}
