// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { DataType } from "../hl7-fhir-r5-core/DataType";

export type { DataType } from "../hl7-fhir-r5-core/DataType";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Money
export interface Money extends DataType {
	currency?: string;
	_currency?: Element;
	value?: number;
	_value?: Element;
}
