// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { DataType } from "../hl7-fhir-r5-core/DataType";

export type { DataType } from "../hl7-fhir-r5-core/DataType";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Period
export interface Period extends DataType {
    end?: string;
    _end?: Element;
    start?: string;
    _start?: Element;
}
