// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { DataType } from "../hl7-fhir-r5-core/DataType";

export type { DataType } from "../hl7-fhir-r5-core/DataType";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Quantity
export interface Quantity extends DataType {
	code?: string;
	_code?: Element;
	comparator?: "<" | "<=" | ">=" | ">" | "ad";
	_comparator?: Element;
	system?: string;
	_system?: Element;
	unit?: string;
	_unit?: Element;
	value?: number;
	_value?: Element;
}
