// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { Base } from "../hl7-fhir-r5-core/Base";
import type { Meta } from "../hl7-fhir-r5-core/Meta";

export type { Base } from "../hl7-fhir-r5-core/Base";
export type { Meta } from "../hl7-fhir-r5-core/Meta";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Resource
export interface Resource extends Base {
	resourceType:
		| "CanonicalResource"
		| "DomainResource"
		| "OperationOutcome"
		| "Resource"
		| "ViewDefinition";

	id?: string;
	_id?: Element;
	implicitRules?: string;
	_implicitRules?: Element;
	language?: string;
	_language?: Element;
	meta?: Meta;
}
export const isResource = (resource: unknown): resource is Resource => {
	return (
		resource !== null &&
		typeof resource === "object" &&
		(resource as { resourceType: string }).resourceType === "Resource"
	);
};
