import "@mcp-b/global";

const pages = [
	{
		name: "resource_browser",
		description: "List of all FHIR resource types",
		path: "/resource",
		tools: [
			"list_resource_types(filter?) - List all FHIR resource types, optionally filter by name",
			"get_favorites() - Get pinned resource types",
			"toggle_favorite(resourceType) - Pin/unpin a resource type",
			"navigate_to_resource_type(resourceType) - Navigate to instances of a resource type",
		],
	},
	{
		name: "resources_list",
		description:
			"List of resources for a specific type. Path param: resourceType",
		path: "/resource/{resourceType}",
		tools: [
			"switch_tab(tab: resources|profiles|extensions) - Switch between tabs",
			"instances_get_search() - Get current FHIR search query string",
			"instances_search(query) - Set FHIR search query and execute",
			"instances_get_results() - Get displayed table data with pagination",
			"instances_get_page() - Get current pagination state",
			"instances_get_selected() - Get IDs of selected resources",
			"instances_select(ids, selected?) - Select/deselect resources by ID",
			"instances_delete_selected() - Delete selected resources",
			"instances_export_selected() - Export selected as FHIR Bundle",
			"instances_change_page(page) - Navigate to a specific page",
			"instances_change_page_size(pageSize: 10|20|30|50|100) - Change page size",
			"instances_navigate_to_resource(id) - Navigate to edit a resource",
			"instances_open_create_page() - Navigate to create a new resource",
			"profiles_list() - List StructureDefinition profiles for the type",
			"profiles_select(url) - Open a profile detail panel",
			"profiles_select_tab(tab: differential|snapshot|fhirschema|structuredefinition) - Switch profile detail tab",
			"search_params_list() - List SearchParameter resources for the type",
		],
	},
	{
		name: "create_resource",
		description: "Form to create a new resource. Path param: resourceType",
		path: "/resource/{resourceType}/create",
		tools: [
			"editor_get_value() - Get editor content",
			"editor_set_value(value) - Set editor content (JSON/YAML)",
			"editor_switch_mode(mode: json|yaml) - Switch between JSON and YAML",
			"editor_format() - Format editor content",
			"editor_save() - Save the resource",
			"editor_get_validation_errors() - Get validation errors",
			"editor_choose_profile(key) - Select a validation profile",
		],
	},
	{
		name: "edit_resource",
		description:
			"Form to edit an existing resource. Path params: resourceType, id",
		path: "/resource/{resourceType}/edit/{id}",
		tools: [
			"editor_switch_tab(tab: edit|history|builder) - Switch between tabs",
			"editor_get_tab() - Get currently active tab",
			"editor_switch_mode(mode: json|yaml) - Switch editor mode",
			"editor_get_mode() - Get current editor mode",
			"editor_get_value() - Get editor content",
			"editor_set_value(value) - Set editor content (JSON/YAML)",
			"editor_format() - Format editor content",
			"editor_save() - Save the resource",
			"editor_delete() - Delete the resource",
			"editor_get_validation_errors() - Get validation errors",
			"editor_toggle_profile_panel() - Toggle profile panel",
			"editor_get_profile() - Get selected profile info",
			"editor_choose_profile(key) - Select a validation profile",
			"history_list_versions() - List all history versions",
			"history_select_version(versionId) - Select a history version",
			"history_get_selected() - Get selected version details",
			"history_get_view_mode() - Get history view mode (raw|diff)",
			"history_switch_view_mode(mode: raw|diff) - Switch history view",
			"history_get_raw_mode() - Get raw view mode (json|yaml)",
			"history_switch_raw_mode(mode: json|yaml) - Switch raw view mode",
			"history_restore() - Restore selected history version",
			"history_get_selected_diff() - Get diff between versions",
			"--- ViewDefinition Builder (builder tab, for ViewDefinition resources) ---",
			"vd_get_view_definition() - Get current ViewDefinition as JSON",
			"vd_set_view_definition(value) - Set ViewDefinition from JSON string",
			"vd_get_resource_type() - Get current resource type",
			"vd_set_resource_type(resourceType) - Set FHIR resource type for the view",
			"vd_run() - Execute ViewDefinition and get results",
			"vd_save() - Save ViewDefinition",
			"vd_materialize(type: view|materialized-view|table) - Materialize as DB view/table",
			"vd_delete() - Delete ViewDefinition",
			"vd_get_run_results() - Get results from last run",
			"vd_get_run_error() - Get errors from last run",
			"vd_get_status() - Get status (dirty, resourceType, hasResults)",
			"vd_switch_builder_tab(tab: form|code|sql) - Switch builder sub-tab",
			"vd_get_builder_tab() - Get active builder sub-tab",
			"vd_toggle_instances_panel() - Toggle instances side panel",
			"vd_get_instances_panel_open() - Check if instances panel is open",
			"vd_instances_search(query) - Search FHIR instances for preview",
			"vd_instances_get_current() - Get current instance as JSON",
			"vd_instances_get_count() - Get total instance count",
			"vd_instances_get_index() - Get current instance index",
			"vd_instances_next() - Navigate to next instance",
			"vd_instances_previous() - Navigate to previous instance",
			"vd_instances_go_to_index(index) - Navigate to instance by index",
			"vd_get_form_tree() - Get form tree with nodeIds for editing",
			"vd_set_name(name) - Set ViewDefinition name",
			"vd_set_status(status: draft|active|retired|unknown) - Set status",
			"vd_add_constant(name?, value?) - Add constant",
			"vd_update_constant(nodeId, field: name|valueString, value) - Update constant",
			"vd_remove_constant(nodeId) - Remove constant",
			"vd_add_where(path?) - Add where condition",
			"vd_update_where(nodeId, path) - Update where condition",
			"vd_remove_where(nodeId) - Remove where condition",
			"vd_add_select(type: column|forEach|forEachOrNull|unionAll, parentNodeId?) - Add select item",
			"vd_remove_select(nodeId) - Remove select item",
			"vd_update_select_expression(nodeId, expression) - Update forEach/forEachOrNull expression",
			"vd_add_column(selectNodeId, name?, path?) - Add column to a select",
			"vd_update_column(selectNodeId, columnNodeId, field: name|path, value) - Update column",
			"vd_remove_column(selectNodeId, columnNodeId) - Remove column",
		],
	},
	{
		name: "rest_console",
		description: "REST API console for executing HTTP requests",
		path: "/rest",
		tools: [
			"toggle_left_menu(open?) - Toggle left sidebar",
			"set_left_menu_tab(tab: history|collections) - Switch left sidebar tab",
			"search_history(query?) - Search request history",
			"select_history_item(id) - Load history item into tab",
			"list_collections() - List saved request collections",
			"save_to_collection(collection?) - Save request to collection",
			"add_collection_entry(collection) - Add empty request to collection",
			"rename_collection(name, newName) - Rename a collection",
			"delete_collection(name) - Delete a collection",
			"rename_snippet(id, newTitle) - Rename a saved request",
			"delete_snippet(id) - Delete a saved request",
			"list_tabs() - List all open request tabs",
			"select_tab(id) - Switch to a tab",
			"add_tab() - Add new empty request tab",
			"close_tab(id?) - Close a tab",
			"close_other_tabs(id?) - Close all tabs except one",
			"close_tabs_to_left(id?) - Close tabs to the left",
			"close_tabs_to_right(id?) - Close tabs to the right",
			"get_raw_request() - Get full raw HTTP request text",
			"set_raw_request(raw) - Set request from raw HTTP text",
			"get_body_mode() - Get body editor mode (json|yaml)",
			"set_body_mode(mode: json|yaml) - Switch body editor mode",
			"format_body() - Format request body",
			"get_request_body() - Get request body",
			"set_request_body(body) - Set request body",
			"get_request_headers() - Get request headers",
			"set_request_headers(headers) - Replace all request headers",
			"toggle_request_header(name, enabled?) - Toggle a request header",
			"get_request_params() - Get query parameters",
			"set_request_params(params) - Replace all query parameters",
			"toggle_request_param(name, enabled?) - Toggle a query parameter",
			"send_request() - Send request and get response",
			"get_response() - Get response data (status, headers, body)",
			"get_response_tab() - Get active response tab",
			"set_response_tab(tab: body|headers|raw|explain) - Switch response tab",
			"get_panel_layout() - Get panel layout",
			"set_panel_layout(layout: vertical|horizontal|request-maximized|response-maximized) - Set panel layout",
		],
	},
	{
		name: "db_console",
		description: "Database SQL console",
		path: "/db-console",
		tools: [
			"execute_sql(query) - Fill editor with SQL and execute",
			"run_query() - Execute current SQL without changing editor",
			"set_query(query) - Set SQL in editor without executing",
			"get_query() - Get current SQL from active tab",
			"format_sql() - Format SQL in editor",
			"list_tabs() - List open SQL editor tabs",
			"select_tab(tab_id) - Switch to a SQL editor tab",
			"add_tab() - Create new empty SQL tab",
			"duplicate_tab(tab_id) - Duplicate a tab",
			"close_tab(tab_id) - Close a tab",
			"close_other_tabs(tab_id) - Close all tabs except one",
			"close_tabs_to_left(tab_id) - Close tabs to the left",
			"close_tabs_to_right(tab_id) - Close tabs to the right",
			"select_table(table) - Select table in sidebar (e.g. 'public.patient')",
			"get_table_info(table) - Get table columns, indexes, size",
			"drop_index(index_name) - Drop a database index",
			"get_active_queries() - Get running database queries",
			"cancel_query(pid) - Cancel a running query by PID",
			"open_sidebar() - Open left sidebar",
			"show_left_menu(tab: history|tables|queries) - Open sidebar on specific tab",
			"toggle_results_panel(action: expand|collapse|maximize|minimize) - Control results panel",
			"show_explain(mode?: visual|raw) - Show query execution plan",
			"show_result() - Switch results panel to Result tab",
			"get_query_status() - Get query execution status",
			"get_results(limit?) - Get query results data",
			"set_row_limit(limit) - Set default row limit (null to disable)",
			"get_row_limit() - Get current row limit",
			"get_history(search?, limit?) - Get SQL query history",
			"open_history_entry(index) - Open query from history by index",
			"list_tables(schema?) - List all database tables by schema",
		],
	},
	{
		name: "fhir_packages",
		description: "List of installed FHIR packages",
		path: "/ig",
		tools: [
			"list_packages(query?) - List installed FHIR packages, optionally filter",
			"sort_packages(column: name|type) - Sort packages by column",
			"select_package(id) - Navigate to package detail (id: name#version)",
			"open_installation_page() - Navigate to import page",
		],
	},
	{
		name: "import_package",
		description: "Import a FHIR package",
		path: "/ig/add",
		tools: [
			"get_package_import_method() - Get current import method",
			"set_package_import_method(method: registry|url|file) - Switch import method",
			"method_registry_search_package(query) - Search FHIR package registry",
			"method_registry_select_package(id) - Toggle package selection (id: name#version)",
			"get_packages_to_install() - Get packages selected for import",
			"method_url_add_url(url) - Add URL to import list",
			"import_packages() - Trigger import of selected packages",
			"get_import_status() - Check import progress",
			"show_import_logs() - Get import log messages",
		],
	},
	{
		name: "package_detail",
		description: "View details of a FHIR package. Path param: packageId",
		path: "/ig/{packageId}",
		tools: [
			"get_active_tab() - Get current tab (canonicals|package-info)",
			"set_active_tab(tab: canonicals|package-info) - Switch tab",
			"get_package_info(format?: visual|json) - Get package metadata",
			"set_package_info_view(view: visual|json) - Switch package info sub-view",
			"search_canonicals(query?, page?) - Search canonical resources in the package",
			"select_canonical(id) - Navigate to a canonical resource",
			"reinstall_package() - Reinstall from registry",
			"delete_package() - Delete the package",
		],
	},
	{
		name: "canonical_resource",
		description:
			"View a canonical resource within a FHIR package. Path params: packageId, resourceType, resourceId",
		path: "/ig/{packageId}/resource/{resourceType}/{resourceId}",
		tools: [
			"get_resource_info() - Get resource name, url, version, type",
			"get_active_view() - Get current view tab",
			"set_active_view(view: json|differential|snapshot|expansion) - Switch view tab",
			"get_resource_json() - Get full FHIR resource JSON",
			"get_structure_elements(type: differential|snapshot) - Get StructureDefinition elements",
			"get_valueset_expansion() - Expand a ValueSet",
			"search_valueset_expansion(filter) - Search within ValueSet expansion",
			"open_in_editor() - Navigate to resource editor",
		],
	},
];

if (navigator.modelContext) {
	navigator.modelContext.registerTool({
		name: "list_pages",
		description:
			"Returns all available pages in the Aidbox UI with their names, descriptions, URL paths, " +
			"and the tools available on each page. Use this to find which page to navigate to for a specific task.",
		inputSchema: { type: "object", properties: {} },
		execute: async () => ({
			content: [
				{
					type: "text" as const,
					text: JSON.stringify(pages, null, 2),
				},
			],
		}),
	});
}
