import { Button } from "@health-samurai/react-components";
import { Link } from "@tanstack/react-router";
import {
	ArrowRight,
	ArrowUpRight,
	BadgeCheck,
	Bell,
	BookOpen,
	Braces,
	Cable,
	Check,
	Code,
	Database,
	FileCog,
	FileText,
	GitBranch,
	Github,
	Hash,
	HeartPulse,
	Package,
	Server,
	Shield,
	SquareTerminal,
	TableProperties,
	Zap,
} from "lucide-react";
import { DataImport } from "./DataImport";
import { restConsoleImage } from "./rest-image";
import { sqlConsoleImage } from "./sql-image";
import { vdBuilderImage } from "./vd-image";

const cardShadow =
	"shadow-[0px_56px_34px_0px_rgba(0,0,0,0.03),0px_25px_25px_0px_rgba(0,0,0,0.04),0px_6px_14px_0px_rgba(0,0,0,0.05)]";

function RestIllustration() {
	return (
		<div
			className={`h-[417px] w-[476px] overflow-hidden rounded-xl border border-border-primary ${cardShadow}`}
		>
			<img
				src={restConsoleImage}
				alt="REST Console"
				className="size-full object-cover"
			/>
		</div>
	);
}

function SqlIllustration() {
	return (
		<div
			className={`h-[357px] w-[476px] overflow-hidden rounded-xl border border-border-primary ${cardShadow}`}
		>
			<img
				src={sqlConsoleImage}
				alt="SQL Console"
				className="size-full object-cover"
			/>
		</div>
	);
}

function VdIllustration() {
	return (
		<div
			className={`h-[361px] w-[476px] overflow-hidden rounded-xl border border-border-primary ${cardShadow}`}
		>
			<img
				src={vdBuilderImage}
				alt="ViewDefinition Builder"
				className="size-full object-cover"
			/>
		</div>
	);
}

function OpenSourceIllustration() {
	return (
		<div
			className={`overflow-hidden rounded-xl border border-border-primary bg-bg-primary ${cardShadow}`}
		>
			<div className="flex items-center gap-2 border-b border-border-primary bg-bg-secondary px-4 py-2.5">
				<div className="size-3 rounded-full bg-red-400" />
				<div className="size-3 rounded-full bg-yellow-400" />
				<div className="size-3 rounded-full bg-green-400" />
				<span className="ml-2 font-mono text-[11px] text-text-tertiary">
					App.tsx
				</span>
			</div>
			<pre className="px-4 py-3 font-mono text-[10px] leading-[1.7]">
				<span className="text-text-tertiary">
					{"// Generated by @atomic-ehr/codegen"}
				</span>
				{"\n"}
				<span className="text-purple-600">import type</span>
				{" { "}
				<span className="text-blue-600">Patient</span>
				{" } "}
				<span className="text-purple-600">from</span>{" "}
				<span className="text-green-600">{'"hl7-fhir-r4-core"'}</span>
				{";\n"}
				<span className="text-purple-600">import</span>
				{" { "}
				<span className="text-blue-600">AidboxClient</span>
				{" } "}
				<span className="text-purple-600">from</span>{" "}
				<span className="text-green-600">
					{'"@health-samurai/aidbox-client"'}
				</span>
				{";\n"}
				<span className="text-purple-600">import</span>
				{" { "}
				<span className="text-blue-600">OperationOutcomeView</span>
				{" } "}
				<span className="text-purple-600">from</span>{" "}
				<span className="text-green-600">
					{'"@health-samurai/react-components"'}
				</span>
				{";\n\n"}
				<span className="text-purple-600">const</span>
				{" result = "}
				<span className="text-purple-600">await</span>
				{" client."}
				<span className="text-blue-600">read</span>
				{"<"}
				<span className="text-blue-600">Patient</span>
				{">({\n  "}
				<span className="text-text-tertiary">type</span>
				{": "}
				<span className="text-green-600">{'"Patient"'}</span>
				{", "}
				<span className="text-text-tertiary">id</span>
				{": "}
				<span className="text-green-600">{'"pt-1"'}</span>
				{",\n});\n\n"}
				<span className="text-purple-600">if</span>
				{" (result."}
				<span className="text-blue-600">isErr</span>
				{"()) {\n  "}
				<span className="text-purple-600">return</span>
				{" <"}
				<span className="text-blue-600">OperationOutcomeView</span>{" "}
				<span className="text-text-tertiary">resource</span>
				{"={result.value.resource} />;\n}"}
			</pre>
		</div>
	);
}

function FeatureSection({
	icon,
	title,
	description,
	features,
	to,
	external,
	cta,
	secondaryTo,
	secondaryCta,
	illustration,
	reverse,
}: {
	icon: React.ReactNode;
	title: string;
	description: string;
	features: string[];
	to: string;
	external?: boolean;
	cta: string;
	secondaryTo?: string;
	secondaryCta?: string;
	illustration?: React.ReactNode;
	reverse?: boolean;
}) {
	const textBlock = (
		<div className="flex flex-col justify-start">
			<div className="flex items-center gap-3 p-2">
				<div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-bg-brand-secondary text-text-brand-primary">
					{icon}
				</div>
				<h2 className="text-2xl font-semibold leading-8 text-text-primary">
					{title}
				</h2>
			</div>
			<div className="pl-2 pt-3">
				<p className="text-base leading-[26px] text-text-secondary">
					{description}
				</p>
				<ul className="mt-7 space-y-2.5 text-sm leading-5 text-text-secondary">
					{features.map((feature) => (
						<li key={feature} className="flex items-start gap-2.5">
							<Check className="mt-0.5 size-4 shrink-0 text-text-brand-primary" />
							<span>{feature}</span>
						</li>
					))}
				</ul>
				<div className="mt-8 flex gap-3">
					{external ? (
						<a href={to} target="_blank" rel="noopener noreferrer">
							<Button variant="secondary">
								{cta}
								<ArrowUpRight className="size-4" />
							</Button>
						</a>
					) : (
						<Link to={to}>
							<Button variant="secondary">
								{cta}
								<ArrowRight className="size-4" />
							</Button>
						</Link>
					)}
					{secondaryTo && secondaryCta && (
						<a href={secondaryTo} target="_blank" rel="noopener noreferrer">
							<Button variant="secondary">
								{secondaryCta}
								<ArrowUpRight className="size-4" />
							</Button>
						</a>
					)}
				</div>
			</div>
		</div>
	);

	const illustrationBlock = (
		<div className="shrink-0 py-[31px]">{illustration}</div>
	);

	const gridCols = reverse
		? "md:grid-cols-[476px_1fr]"
		: "md:grid-cols-[1fr_476px]";

	return (
		<section
			className={`grid grid-cols-1 items-center gap-12 ${gridCols} md:gap-16`}
		>
			{reverse ? (
				<>
					{illustrationBlock}
					{textBlock}
				</>
			) : (
				<>
					{textBlock}
					{illustrationBlock}
				</>
			)}
		</section>
	);
}

// --- Module Cards (ported from old home page) ---

interface CardButtonData {
	text: string;
	href: string;
	icon: React.ReactNode;
}

interface CardData {
	heading: string;
	icon?: React.ReactNode;
	iconBorder?: boolean;
	description?: string;
	buttons: CardButtonData[];
}

function ModuleCard({
	heading,
	icon,
	iconBorder,
	description,
	buttons,
}: CardData) {
	return (
		<div className="flex h-full flex-1 flex-col justify-between gap-4 rounded-lg bg-bg-secondary p-5">
			<div className="flex flex-col items-start gap-2">
				<div className="flex items-center gap-2">
					{icon && (
						<div
							className={`flex size-11 shrink-0 items-center justify-center text-text-secondary ${iconBorder ? "rounded-full" : ""}`}
						>
							{icon}
						</div>
					)}
					<span className="text-sm font-semibold text-text-primary">
						{heading}
					</span>
				</div>
				{description && (
					<p className="text-xs leading-5 text-text-tertiary">{description}</p>
				)}
			</div>
			<div className="flex flex-wrap items-start gap-2">
				{buttons.map((button) => (
					<a
						key={button.text}
						href={button.href}
						target="_blank"
						rel="noopener noreferrer"
					>
						<Button variant="secondary" size="small">
							{button.icon}
							<span>{button.text}</span>
						</Button>
					</a>
				))}
			</div>
		</div>
	);
}

const aidboxModulesData: CardData[] = [
	{
		heading: "Security & Access control",
		icon: <Shield className="size-5" />,
		iconBorder: true,
		description:
			"Authenticate users via OAuth 2.0 and external identity providers. Define roles and access policies at any level of granularity.",
		buttons: [
			{
				text: "Docs",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/modules/access-control",
			},
		],
	},
	{
		heading: "SQL on FHIR engine",
		icon: <Database className="size-5" />,
		iconBorder: true,
		description:
			"Turn nested FHIR data into simple tables for analytics using ViewDefinitions and standard SQL.",
		buttons: [
			{
				text: "Builder",
				icon: <ArrowUpRight className="size-3.5" />,
				href: "/u/resource/ViewDefinition",
			},
			{
				text: "Docs",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/storage-1/sql-on-fhir",
			},
		],
	},
	{
		heading: "IG loader",
		icon: <GitBranch className="size-5" />,
		iconBorder: true,
		description:
			"Load FHIR Implementation Guides with automatic dependency resolution. Supports NPM packages and CRUD API.",
		buttons: [
			{
				text: "Load IG",
				icon: <ArrowUpRight className="size-3.5" />,
				href: "/u/ig",
			},
			{
				text: "Docs",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/modules/profiling-and-validation/fhir-schema-validator/upload-fhir-implementation-guide",
			},
		],
	},
	{
		heading: "Forms",
		icon: <FileText className="size-5" />,
		iconBorder: true,
		description:
			"No-code form builder for digital health forms based on FHIR SDC with data extraction and population.",
		buttons: [
			{
				text: "Try",
				icon: <ArrowUpRight className="size-3.5" />,
				href: "/ui/sdc",
			},
			{
				text: "Docs",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/modules/aidbox-forms",
			},
		],
	},
	{
		heading: "Subscriptions",
		icon: <Bell className="size-5" />,
		iconBorder: true,
		description:
			"Real-time notifications on resource changes via Kafka, webhooks, and cloud messaging.",
		buttons: [
			{
				text: "Tutorial",
				icon: <ArrowUpRight className="size-3.5" />,
				href: "https://docs.aidbox.app/modules/topic-based-subscriptions/wip-dynamic-subscriptiontopic-with-destinations/tutorial-produce-questionnaireresponse-to-kafka-topic",
			},
			{
				text: "Docs",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/modules/topic-based-subscriptions",
			},
		],
	},
	{
		heading: "Validation engine",
		icon: <BadgeCheck className="size-5" />,
		iconBorder: true,
		description:
			"Validate resources against FHIR and custom profiles to ensure data quality and compliance.",
		buttons: [
			{
				text: "Try Engine",
				icon: <ArrowUpRight className="size-3.5" />,
				href: "/u/rest",
			},
			{
				text: "Docs",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/modules/profiling-and-validation/fhir-schema-validator",
			},
		],
	},
	{
		heading: "Integration toolkit",
		icon: <Cable className="size-5" />,
		iconBorder: true,
		description:
			"Convert and ingest data from C-CDA, HL7 v2, and X12 formats with customizable mappings.",
		buttons: [
			{
				text: "HL7 v2",
				icon: <ArrowUpRight className="size-3.5" />,
				href: "/u/resource/Hl7v2Message",
			},
			{
				text: "CCDA",
				icon: <ArrowUpRight className="size-3.5" />,
				href: "https://ccda.aidbox.app/v2/ccda-fhir",
			},
			{
				text: "Docs",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/modules/integration-toolkit",
			},
		],
	},
];

const clientLibrariesData: CardData[] = [
	{
		heading: "JavaScript",
		icon: <Braces className="size-5" />,
		buttons: [
			{
				text: "About JavaScript SDK",
				icon: <BookOpen className="size-3.5" />,
				href: "https://docs.aidbox.app/app-development/aidbox-sdk/aidbox-javascript-sdk",
			},
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/aidbox-sdk-js",
			},
			{
				text: "NPM",
				icon: <Package className="size-3.5" />,
				href: "https://www.npmjs.com/package/@aidbox/sdk-r4",
			},
		],
	},
	{
		heading: "Python",
		icon: <Code className="size-5" />,
		buttons: [
			{
				text: "About Python SDK",
				icon: <BookOpen className="size-3.5" />,
				href: "https://www.health-samurai.io/docs/aidbox/getting-started/python",
			},
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/aidbox-python",
			},
		],
	},
	{
		heading: ".NET",
		icon: <Hash className="size-5" />,
		buttons: [
			{
				text: "About .NET SDK",
				icon: <BookOpen className="size-3.5" />,
				href: "https://github.com/Aidbox/aidbox-dotnet/blob/main/README.MD",
			},
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/aidbox-dotnet/",
			},
		],
	},
	{
		heading: "SDK Generator",
		icon: <FileCog className="size-5" />,
		iconBorder: true,
		buttons: [
			{
				text: "About SDK Generator",
				icon: <BookOpen className="size-3.5" />,
				href: "https://github.com/Aidbox/aidbox-sdk/blob/main/README.md",
			},
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/aidbox-sdk",
			},
		],
	},
];

const sampleAppsData: CardData[] = [
	{
		heading: "BEDA EMR",
		icon: <HeartPulse className="size-5" />,
		description:
			"Clean and powerful frontend for Electronic Medical Records. Open-source. Customizable. Leverages HL7 FHIR standard as a data model and SDC IG for form management.",
		buttons: [
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/examples/tree/main/aidbox-integrations/BedaEmr",
			},
		],
	},
	{
		heading: "Custom resources",
		icon: <Braces className="size-5" />,
		description:
			"Custom resources demonstration on the minimalistic JavaScript example project which implemented the typical flow for notifications.",
		buttons: [
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/examples/tree/main/aidbox-features/aidbox-notify-via-custom-resources",
			},
		],
	},
	{
		heading: "IPS IG",
		icon: <Server className="size-5" />,
		description:
			"Pre-configured Aidbox instance and implementation of $summary operation defined by IPS.",
		buttons: [
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/examples/tree/main/aidbox-custom-operations/ips-ig",
			},
		],
	},
	{
		heading: "Aidbox Forms React",
		icon: <FileText className="size-5" />,
		description: "Example of integration Aidbox Forms Renderer with React.js",
		buttons: [
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/examples/tree/main/aidbox-forms/aidbox-forms-renderer-react",
			},
		],
	},
	{
		heading: "Aidbox topic-based subscriptions",
		icon: <Zap className="size-5" />,
		description:
			"This example showcases Aidbox SubscriptionTopic producing data to Kafka.",
		buttons: [
			{
				text: "GitHub",
				icon: <Github className="size-3.5" />,
				href: "https://github.com/Aidbox/examples/tree/main/aidbox-features/aidbox-subscriptions-to-kafka",
			},
		],
	},
];

export function HomePage() {
	return (
		<div className="h-full overflow-auto px-8">
			<div className="mx-auto max-w-[1016px] py-20">
				{/* Hero */}
				<div className="mb-[116px] text-center">
					<h1 className="text-4xl font-bold tracking-tight text-text-primary md:text-5xl">
						The new Aidbox UI
					</h1>
					<p className="mx-auto mt-6 text-lg leading-relaxed text-text-secondary">
						A modern, open-source developer console for Aidbox.
						<br />
						Explore FHIR resources, run queries, and build views — all from your
						browser.
					</p>
				</div>

				{/* Feature sections */}
				<div className="flex flex-col gap-[121px]">
					<FeatureSection
						icon={<Github className="size-5" />}
						title="Open Source"
						description="Aidbox UI is fully open source. Fork it, extend it, contribute back. Built with React, TypeScript, and a shared component library."
						features={[
							"Full source code on GitHub",
							"Reusable React component library",
							"Storybook with live examples",
						]}
						to="https://github.com/HealthSamurai/aidbox-ui"
						external
						cta="Aidbox UI"
						secondaryTo="https://github.com/HealthSamurai/aidbox-ts-sdk/tree/master/packages/react-components"
						secondaryCta="React Components"
						illustration={<OpenSourceIllustration />}
					/>

					<FeatureSection
						icon={<SquareTerminal className="size-5" />}
						title="REST Console"
						description="New REST client with deep FHIR integration. Test APIs, explore endpoints, and debug requests without leaving Aidbox."
						features={[
							"Multiple tabs for parallel requests",
							"Autocomplete for URLs, parameters, and headers",
							"Saved collections and request history",
						]}
						to="/rest"
						cta="Try REST console"
						illustration={<RestIllustration />}
						reverse
					/>

					<FeatureSection
						icon={<Database className="size-5" />}
						title="SQL Console"
						description="Powerful SQL editor for direct database access. Query your data, explore schema, and monitor performance."
						features={[
							"Multiple tabs for parallel queries",
							"Autocomplete for tables, columns, and functions",
							"Built-in database structure explorer",
							"Running queries monitor",
							"Table and index information",
						]}
						to="/db-console"
						cta="Try SQL console"
						illustration={<SqlIllustration />}
					/>

					<FeatureSection
						icon={<TableProperties className="size-5" />}
						title="ViewDefinition builder"
						description="Visual builder for FHIR ViewDefinitions. Create flat, queryable views over FHIR resources for analytics and reporting."
						features={[
							"Visual column editor with live preview",
							"FHIRPath expression support",
							"JSON and table output modes",
						]}
						to="/resource/ViewDefinition"
						cta="Try ViewDefinition builder"
						illustration={<VdIllustration />}
						reverse
					/>
				</div>

				{/* Import Data */}
				<div className="mt-32">
					<DataImport />
				</div>

				{/* Aidbox Modules */}
				<div className="mt-32 flex flex-col gap-5">
					<div className="flex flex-col gap-3">
						<h2 className="text-2xl font-semibold text-text-primary">
							Aidbox modules
						</h2>
						<p className="text-base leading-relaxed text-text-secondary">
							Use additional modules to build secure and performant FHIR-first
							digital health solutions
						</p>
					</div>
					<div className="grid grid-cols-1 items-stretch gap-2 md:grid-cols-2 lg:grid-cols-3 [&>*:last-child:nth-child(3n+1)]:lg:col-start-2">
						{aidboxModulesData.map((card) => (
							<ModuleCard key={card.heading} {...card} />
						))}
					</div>
				</div>

				{/* Client Libraries */}
				<div className="mt-32 flex flex-col gap-5">
					<div className="flex flex-col gap-3">
						<h2 className="text-2xl font-semibold text-text-primary">
							Client libraries
						</h2>
						<p className="text-base leading-relaxed text-text-secondary">
							Connect your project to Aidbox using official SDKs for your
							preferred language
						</p>
					</div>
					<div className="grid grid-cols-1 items-stretch gap-2 md:grid-cols-2 xl:grid-cols-4">
						{clientLibrariesData.map((card) => (
							<ModuleCard key={card.heading} {...card} />
						))}
					</div>
				</div>

				{/* Sample Apps */}
				<div className="mt-32 flex flex-col gap-5">
					<div className="flex flex-col gap-3">
						<h2 className="text-2xl font-semibold text-text-primary">
							Sample Apps
						</h2>
						<p className="text-base leading-relaxed text-text-secondary">
							Explore example projects to jumpstart your development with Aidbox
						</p>
					</div>
					<div className="grid grid-cols-1 items-stretch gap-2 md:grid-cols-2 lg:grid-cols-3">
						{sampleAppsData.map((card) => (
							<ModuleCard key={card.heading} {...card} />
						))}
					</div>
				</div>
			</div>
		</div>
	);
}
