/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestRouteImport } from './routes/rest'
import { Route as ResourceRouteImport } from './routes/resource'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourceIndexRouteImport } from './routes/resource.index'
import { Route as ResourceCreateResourceTypeRouteImport } from './routes/resource.create.$resourceType'
import { Route as ResourceListResourceTypeIndexRouteImport } from './routes/resource.list.$resourceType.index'
import { Route as ResourceEditResourceTypeIdRouteImport } from './routes/resource.edit.$resourceType.$id'

const RestRoute = RestRouteImport.update({
  id: '/rest',
  path: '/rest',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceRoute = ResourceRouteImport.update({
  id: '/resource',
  path: '/resource',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceIndexRoute = ResourceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourceRoute,
} as any)
const ResourceCreateResourceTypeRoute =
  ResourceCreateResourceTypeRouteImport.update({
    id: '/create/$resourceType',
    path: '/create/$resourceType',
    getParentRoute: () => ResourceRoute,
  } as any)
const ResourceListResourceTypeIndexRoute =
  ResourceListResourceTypeIndexRouteImport.update({
    id: '/list/$resourceType/',
    path: '/list/$resourceType/',
    getParentRoute: () => ResourceRoute,
  } as any)
const ResourceEditResourceTypeIdRoute =
  ResourceEditResourceTypeIdRouteImport.update({
    id: '/edit/$resourceType/$id',
    path: '/edit/$resourceType/$id',
    getParentRoute: () => ResourceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resource': typeof ResourceRouteWithChildren
  '/rest': typeof RestRoute
  '/resource/': typeof ResourceIndexRoute
  '/resource/create/$resourceType': typeof ResourceCreateResourceTypeRoute
  '/resource/edit/$resourceType/$id': typeof ResourceEditResourceTypeIdRoute
  '/resource/list/$resourceType': typeof ResourceListResourceTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rest': typeof RestRoute
  '/resource': typeof ResourceIndexRoute
  '/resource/create/$resourceType': typeof ResourceCreateResourceTypeRoute
  '/resource/edit/$resourceType/$id': typeof ResourceEditResourceTypeIdRoute
  '/resource/list/$resourceType': typeof ResourceListResourceTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resource': typeof ResourceRouteWithChildren
  '/rest': typeof RestRoute
  '/resource/': typeof ResourceIndexRoute
  '/resource/create/$resourceType': typeof ResourceCreateResourceTypeRoute
  '/resource/edit/$resourceType/$id': typeof ResourceEditResourceTypeIdRoute
  '/resource/list/$resourceType/': typeof ResourceListResourceTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resource'
    | '/rest'
    | '/resource/'
    | '/resource/create/$resourceType'
    | '/resource/edit/$resourceType/$id'
    | '/resource/list/$resourceType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rest'
    | '/resource'
    | '/resource/create/$resourceType'
    | '/resource/edit/$resourceType/$id'
    | '/resource/list/$resourceType'
  id:
    | '__root__'
    | '/'
    | '/resource'
    | '/rest'
    | '/resource/'
    | '/resource/create/$resourceType'
    | '/resource/edit/$resourceType/$id'
    | '/resource/list/$resourceType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourceRoute: typeof ResourceRouteWithChildren
  RestRoute: typeof RestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rest': {
      id: '/rest'
      path: '/rest'
      fullPath: '/rest'
      preLoaderRoute: typeof RestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource': {
      id: '/resource'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof ResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/': {
      id: '/resource/'
      path: '/'
      fullPath: '/resource/'
      preLoaderRoute: typeof ResourceIndexRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/resource/create/$resourceType': {
      id: '/resource/create/$resourceType'
      path: '/create/$resourceType'
      fullPath: '/resource/create/$resourceType'
      preLoaderRoute: typeof ResourceCreateResourceTypeRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/resource/list/$resourceType/': {
      id: '/resource/list/$resourceType/'
      path: '/list/$resourceType'
      fullPath: '/resource/list/$resourceType'
      preLoaderRoute: typeof ResourceListResourceTypeIndexRouteImport
      parentRoute: typeof ResourceRoute
    }
    '/resource/edit/$resourceType/$id': {
      id: '/resource/edit/$resourceType/$id'
      path: '/edit/$resourceType/$id'
      fullPath: '/resource/edit/$resourceType/$id'
      preLoaderRoute: typeof ResourceEditResourceTypeIdRouteImport
      parentRoute: typeof ResourceRoute
    }
  }
}

interface ResourceRouteChildren {
  ResourceIndexRoute: typeof ResourceIndexRoute
  ResourceCreateResourceTypeRoute: typeof ResourceCreateResourceTypeRoute
  ResourceEditResourceTypeIdRoute: typeof ResourceEditResourceTypeIdRoute
  ResourceListResourceTypeIndexRoute: typeof ResourceListResourceTypeIndexRoute
}

const ResourceRouteChildren: ResourceRouteChildren = {
  ResourceIndexRoute: ResourceIndexRoute,
  ResourceCreateResourceTypeRoute: ResourceCreateResourceTypeRoute,
  ResourceEditResourceTypeIdRoute: ResourceEditResourceTypeIdRoute,
  ResourceListResourceTypeIndexRoute: ResourceListResourceTypeIndexRoute,
}

const ResourceRouteWithChildren = ResourceRoute._addFileChildren(
  ResourceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourceRoute: ResourceRouteWithChildren,
  RestRoute: RestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
